---
engines:
  duplication:
    enabled: true
    config:
      languages:
        - ruby
    exclude_paths:
      - 'test/**/*'
      - 'lib/idcf/cli/validate/define/**/*'
  fixme:
    enabled: true
  rubocop:
    enabled: true
  structure:
    exclude_paths:
      - 'test/**/*'
ratings:
  paths:
    - "**.rb"
checks:
  argument-count:
    config:
      threshold: 6
  method-complexity:
      config:
        threshold: 9

exclude_paths:
  - vendor/bundle
  - .idea
  - bin
  - doc
  - output
