AllCops:
  TargetRubyVersion: 2.2
Metrics/BlockLength:
  Exclude:
    - '*.gemspec'
    - 'test/**/*'
Metrics/LineLength:
  Exclude:
    - 'test/**/*'
Metrics/MethodLength:
  Max: 14
  Exclude:
    - 'test/**/*'
Metrics/ClassLength:
  Exclude:
    - 'test/**/*'
Style/IdenticalConditionalBranches:
  Exclude:
    - 'test/**/*'
Metrics/PerceivedComplexity:
  Exclude:
    - 'test/**/*'
Metrics/AbcSize:
  Exclude:
    - 'test/**/*'
LineLength:
  Max: 100
  Exclude:
    - 'test/**/*'
Style/ClassLength:
  Max: 150
  Exclude:
    - 'test/**/*'
Style/ModuleLength:
  Max: 150
  Exclude:
    - 'test/**/*'
ParameterLists:
  Max: 6
Style/DoubleNegation:
  Enabled: false